<a href="https://colab.research.google.com/github/Tsukkei/CCMACLRL_EXAM_COM221ML/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

## Dataset File

In [ ]:

dataset_url = 'https://github.com/robitussin/CCMACLRL_EXAM/blob/a46a4e2a001dedaefc9b431d480b508ce86c2d96/datasets/train.csv?raw=true'
df = pd.read_csv(dataset_url)

## Test File

In [ ]:
test_url = 'https://github.com/robitussin/CCMACLRL_EXAM/blob/a46a4e2a001dedaefc9b431d480b508ce86c2d96/datasets/test.csv?raw=true'
dt=pd.read_csv(test_url)

dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  object
 2   model         125690 non-null  object
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     122307 non-null  object
 6   engine        125690 non-null  object
 7   transmission  125690 non-null  object
 8   ext_col       125690 non-null  object
 9   int_col       125690 non-null  object
 10  accident      124058 non-null  object
 11  clean_title   111451 non-null  object
dtypes: int64(3), object(9)
memory usage: 11.5+ MB

## Sample Submission File

In [ ]:
sample_submission_url = 'https://github.com/robitussin/CCMACLRL_EXAM/blob/a46a4e2a001dedaefc9b431d480b508ce86c2d96/datasets/sample_submission.csv?raw=true'

sf=pd.read_csv(sample_submission_url)

##Check for missing data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  object
 2   model         188533 non-null  object
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(4), object(9)
memory usage: 18.7+ MB

In [ ]:
df.isnull().sum() #checking for missing data

id                  0
brand               0
model               0
model_year          0
milage              0
fuel_type        5083
engine              0
transmission        0
ext_col             0
int_col             0
accident         2452
clean_title     21419
price               0
dtype: int64

In [ ]:
df.describe()

                  id     model_year         milage         price
count  188533.000000  188533.000000  188533.000000  1.885330e+05
mean    94266.000000    2015.829998   65705.295174  4.387802e+04
std     54424.933488       5.660967   49798.158076  7.881952e+04
min         0.000000    1974.000000     100.000000  2.000000e+03
25%     47133.000000    2013.000000   24115.000000  1.700000e+04
50%     94266.000000    2017.000000   57785.000000  3.082500e+04
75%    141399.000000    2020.000000   95400.000000  4.990000e+04
max    188532.000000    2024.000000  405000.000000  2.954083e+06

##Drop the missing data

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

id              0
brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64

In [ ]:
df.describe()

                  id     model_year         milage         price
count  162610.000000  162610.000000  162610.000000  1.626100e+05
mean    94197.039137    2015.158822   71105.487086  4.081699e+04
std     54467.770815       5.699531   50157.874111  7.653857e+04
min         0.000000    1974.000000     100.000000  2.000000e+03
25%     47026.250000    2012.000000   29000.000000  1.570000e+04
50%     94139.000000    2016.000000   64300.000000  2.850000e+04
75%    141421.750000    2019.000000  101000.000000  4.699900e+04
max    188532.000000    2024.000000  405000.000000  2.954083e+06

##Feature Engineering

In [ ]:
df.sample(20)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
47888,47888,Land,Rover Range Rover Evoque S,2016,74139,Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,Black,Black,None reported,Yes,29995
61821,61821,Hyundai,Genesis 3.8,2012,89726,Gasoline,311.0HP 3.8L V6 Cylinder Engine Gasoline Fuel,A/T,White,Black,None reported,Yes,35000
1227,1227,Mercedes-Benz,Metris Base,2022,26500,Gasoline,2.0L I4 16V GDI DOHC Turbo,9-Speed Automatic,Black,Black,None reported,Yes,62425
51857,51857,Ford,F-250 XLT Crew Cab Super Duty,2008,157500,Gasoline,300.0HP 5.4L 8 Cylinder Engine Gasoline Fuel,A/T,Red,Black,At least 1 accident or damage reported,Yes,7900
33833,33833,Aston,Martin Vantage GT Base,2015,76009,Gasoline,420.0HP 4.7L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,Gray,Black,None reported,Yes,40599
161447,161447,Ford,F-150 Lariat,2021,65441,Gasoline,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Gray,Black,None reported,Yes,41900
63264,63264,BMW,435 Gran Coupe i,2017,77856,Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,20990
174444,174444,Ford,F-150 Platinum,2018,30600,Gasoline,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,6-Speed A/T,Black,Brown,None reported,Yes,86000
93424,93424,Land,Rover Range Rover Sport SVR Carbon Edition,2020,29000,Gasoline,575.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,A/T,White,Black,None reported,Yes,68000
40566,40566,Mercedes-Benz,E-Class E 350,2014,94500,Gasoline,302.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,17000
142712,142712,Ford,Transit Connect XL,2020,61491,E85 Flex Fuel,169.0HP 2.5L 4 Cylinder Engine Flex Fuel Capab...,A/T,Gray,Black,At least 1 accident or damage reported,Yes,29900
175621,175621,Toyota,Tundra SR5 Access Cab,2020,17000,Gasoline,389.0HP 3.4L V6 Cylinder Engine Gasoline Fuel,A/T,White,Black,At least 1 accident or damage reported,Yes,47000
45088,45088,Porsche,911 Carrera 4S,2016,41515,Gasoline,3.0L H6 24V GDI DOHC Twin Turbo,7-Speed Manual,Black,Black,None reported,Yes,79995
64899,64899,Mercedes-Benz,C-Class C 300 4MATIC Sport,2017,49000,Gasoline,241.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,Yes,26000
163173,163173,Mercedes-Benz,SL-Class SL550 Roadster,2008,213000,Gasoline,382.0HP 5.5L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Black,None reported,Yes,28500
150320,150320,Ford,F-250 XLT,2014,102604,E85 Flex Fuel,385.0HP 6.2L 8 Cylinder Engine Flex Fuel Capab...,6-Speed A/T,White,Gray,None reported,Yes,33995
55184,55184,Lincoln,MKZ Reserve I,2011,185000,Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,None reported,Yes,9000
51318,51318,Acura,ILX Technology Plus Package,2016,89144,Gasoline,201.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,A/T,Silver,–,None reported,Yes,11499
128515,128515,Mercedes-Benz,Sprinter 2500 Standard Roof,2022,25548,Diesel,3.0 Liter,Automatic,Navarra Blue Metallic,Saiga Beige,None reported,Yes,35999
59795,59795,Lexus,GX 460 Premium,2017,71750,Gasoline,301.0HP 4.6L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,Black,Black,None reported,Yes,32000

In [ ]:
##Creating the car age

from datetime import datetime

current_year = datetime.now().year
df['car_age'] = current_year - df['model_year']
dt['car_age'] = current_year - dt['model_year']

In [ ]:
df.head(10)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200,17
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999,22
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900,22
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000,7
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500,3
5,5,Audi,A6 2.0T Sport,2018,40950,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,White,–,None reported,Yes,29950,6
6,6,Audi,A8 L 3.0T,2016,62200,Gasoline,333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Black,Black,None reported,Yes,28500,8
7,7,Chevrolet,Silverado 1500 1LZ,2016,102604,E85 Flex Fuel,355.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,White,Gray,None reported,Yes,12500,8
8,8,Ford,F-150 XLT,2020,38352,Gasoline,2.7L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,Snowflake White Pearl Metallic,Black,None reported,Yes,62890,4
9,9,BMW,M4 Base,2015,74850,Gasoline,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Black,Blue,None reported,Yes,4000,9

In [ ]:
df.head(5)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200,17
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999,22
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900,22
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000,7
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500,3

In [ ]:

df[object_columns]

,brand,model,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,MINI,Cooper S Base,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes
1,Lincoln,LS V8,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes
2,Chevrolet,Silverado 2500 LT,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes
3,Genesis,G90 5.0 Ultimate,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes
4,Mercedes-Benz,Metris Base,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes
...,...,...,...,...,...,...,...,...,...
188527,Chevrolet,Camaro Z28,Gasoline,310.0HP 5.7L 8 Cylinder Engine Gasoline Fuel,A/T,White,Gray,None reported,Yes
188528,Cadillac,Escalade ESV Platinum,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Beige,None reported,Yes
188529,Mercedes-Benz,AMG C 43 AMG C 43 4MATIC,Gasoline,385.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Black,At least 1 accident or damage reported,Yes
188530,Mercedes-Benz,AMG GLC 63 Base 4MATIC,Gasoline,469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,White,Black,None reported,Yes
188532,Porsche,Macan Base,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Black,None reported,Yes

In [ ]:
df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200,17
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999,22
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900,22
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000,7
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500,3

In [ ]:
df['accident'].value_counts()

accident
None reported                             122411
At least 1 accident or damage reported     40199
Name: count, dtype: int64

In [ ]:

df['accident'] = df['accident'].replace({'None reported': 0,'At least 1 accident or damage reported': 1})

dt['accident'] = dt['accident'].replace({'None reported': 0,'At least 1 accident or damage reported': 1})

In [ ]:
df['brand'].value_counts()

brand
Ford             21348
Mercedes-Benz    16530
BMW              15461
Chevrolet        15170
Audi              9111
Porsche           9025
Toyota            7862
Land              7857
Lexus             7622
Jeep              5330
Cadillac          4330
Nissan            3536
RAM               3391
INFINITI          3103
GMC               2970
Dodge             2967
Mazda             2393
Subaru            2281
Lincoln           2261
Honda             1828
Acura             1738
Hyundai           1714
Kia               1659
Volkswagen        1608
Jaguar            1064
MINI              1035
Bentley           1012
Maserati           836
Genesis            826
Buick              720
Chrysler           693
Volvo              656
Mitsubishi         532
Pontiac            530
Rolls-Royce        521
Hummer             515
Alfa               508
Lamborghini        500
Tesla              343
Ferrari            271
Aston              216
McLaren            188
Saturn             144
Scion              114
Rivian              85
Mercury             55
Lotus               48
FIAT                37
Saab                22
Lucid               17
Plymouth             7
Suzuki               6
Bugatti              5
Karma                4
Maybach              3
Polestar             1
smart                1
Name: count, dtype: int64

In [ ]:
df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,0,Yes,4200,17
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,1,Yes,4999,22
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,0,Yes,13900,22
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,0,Yes,45000,7
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,0,Yes,97500,3

In [ ]:
df['transmission'].value_counts()

transmission
A/T                                                   46931
8-Speed A/T                                           20194
Transmission w/Dual Shift Mode                        18972
6-Speed A/T                                           17859
6-Speed M/T                                           11833
7-Speed A/T                                           10950
10-Speed A/T                                           7915
9-Speed A/T                                            3802
8-Speed Automatic                                      3728
5-Speed A/T                                            3172
4-Speed A/T                                            2525
5-Speed M/T                                            2380
10-Speed Automatic                                     2178
CVT Transmission                                       1949
6-Speed Automatic                                      1709
Automatic                                              1650
9-Speed Automatic                                      1290
M/T                                                    1146
7-Speed Automatic with Auto-Shift                       516
7-Speed M/T                                             340
Automatic CVT                                           299
8-Speed Automatic with Auto-Shift                       242
1-Speed A/T                                             192
Transmission Overdrive Switch                           156
6-Speed Manual                                          109
7-Speed Automatic                                       102
5-Speed Automatic                                        89
7-Speed Manual                                           68
6-Speed Automatic with Auto-Shift                        60
4-Speed Automatic                                        31
1-Speed Automatic                                        29
–                                                        26
6-Speed Electronically Controlled Automatic with O       20
7-Speed                                                  19
10-Speed Automatic with Overdrive                        19
2-Speed A/T                                              15
F                                                        15
6-Speed                                                  13
9-Speed Automatic with Auto-Shift                        12
2                                                        11
7-Speed DCT Automatic                                    10
Variable                                                  5
Manual                                                    5
8-Speed Manual                                            5
CVT-F                                                     4
6 Speed At/Mt                                             3
6 Speed Mt                                                3
2-Speed Automatic                                         3
Single-Speed Fixed Gear                                   2
8-SPEED A/T                                               2
SCHEDULED FOR OR IN PRODUCTION                            1
8-SPEED AT                                                1
Name: count, dtype: int64

In [ ]:
df['clean_title'].value_counts()

clean_title
Yes    162610
Name: count, dtype: int64

In [ ]:
df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,0,Yes,4200,17
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,1,Yes,4999,22
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,0,Yes,13900,22
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,0,Yes,45000,7
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,0,Yes,97500,3

In [ ]:
df['transmission'].value_counts()

transmission
A/T                                                   46931
8-Speed A/T                                           20194
Transmission w/Dual Shift Mode                        18972
6-Speed A/T                                           17859
6-Speed M/T                                           11833
7-Speed A/T                                           10950
10-Speed A/T                                           7915
9-Speed A/T                                            3802
8-Speed Automatic                                      3728
5-Speed A/T                                            3172
4-Speed A/T                                            2525
5-Speed M/T                                            2380
10-Speed Automatic                                     2178
CVT Transmission                                       1949
6-Speed Automatic                                      1709
Automatic                                              1650
9-Speed Automatic                                      1290
M/T                                                    1146
7-Speed Automatic with Auto-Shift                       516
7-Speed M/T                                             340
Automatic CVT                                           299
8-Speed Automatic with Auto-Shift                       242
1-Speed A/T                                             192
Transmission Overdrive Switch                           156
6-Speed Manual                                          109
7-Speed Automatic                                       102
5-Speed Automatic                                        89
7-Speed Manual                                           68
6-Speed Automatic with Auto-Shift                        60
4-Speed Automatic                                        31
1-Speed Automatic                                        29
–                                                        26
6-Speed Electronically Controlled Automatic with O       20
7-Speed                                                  19
10-Speed Automatic with Overdrive                        19
2-Speed A/T                                              15
F                                                        15
6-Speed                                                  13
9-Speed Automatic with Auto-Shift                        12
2                                                        11
7-Speed DCT Automatic                                    10
Variable                                                  5
Manual                                                    5
8-Speed Manual                                            5
CVT-F                                                     4
6 Speed At/Mt                                             3
6 Speed Mt                                                3
2-Speed Automatic                                         3
Single-Speed Fixed Gear                                   2
8-SPEED A/T                                               2
SCHEDULED FOR OR IN PRODUCTION                            1
8-SPEED AT                                                1
Name: count, dtype: int64

In [ ]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  object
 2   model         125690 non-null  object
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     122307 non-null  object
 6   engine        125690 non-null  object
 7   transmission  125690 non-null  object
 8   ext_col       125690 non-null  object
 9   int_col       125690 non-null  object
 10  accident      124058 non-null  float64
 11  clean_title   111451 non-null  object
 12  car_age       125690 non-null  int64
dtypes: float64(1), int64(4), object(8)
memory usage: 12.5+ MB

In [ ]:
df.loc[df['transmission'].str.contains('Manual| M/T|Mt', na=False ), 'transmission'] = 'M/T'
df.loc[df['transmission'].str.contains('Automatic| A/T|AT', na=False ), 'transmission'] = 'A/T'

dt.loc[dt['transmission'].str.contains('Manual| M/T|Mt', na=False ), 'transmission'] = 'M/T'
dt.loc[dt['transmission'].str.contains('Automatic| A/T|AT', na=False ), 'transmission'] = 'A/T'

In [ ]:
df['transmission'].value_counts()

transmission
A/T                               125545
Transmission w/Dual Shift Mode     18972
M/T                                15892
CVT Transmission                    1949
Transmission Overdrive Switch        156
–                                     26
7-Speed                               19
F                                     15
6-Speed                               13
2                                     11
Variable                               5
CVT-F                                  4
Single-Speed Fixed Gear                2
SCHEDULED FOR OR IN PRODUCTION         1
Name: count, dtype: int64

In [ ]:
df=df[df['transmission'] != 'SCHEDULED FOR OR IN PRODUCTION']
df=df[df['transmission'] != 'Single-Speed Fixed Gear']
# dt=dt[dt['transmission'] != 'SCHEDULED FOR OR IN PRODUCTION']
# dt=dt[dt['transmission'] != 'Single-Speed Fixed Gear']


other_values = ['Transmission Overdrive Switch', '–', '7-Speed','F', '6-Speed', '2', 'Variable', 'CVT-F']
df['transmission'] =df['transmission'].replace(other_values, 'Unclassified')

dt['transmission'] =dt['transmission'].replace(other_values, 'Unclassified')

In [ ]:
df['transmission'].value_counts()

transmission
A/T                               125545
Transmission w/Dual Shift Mode     18972
M/T                                15892
CVT Transmission                    1949
Unclassified                         249
Name: count, dtype: int64

In [ ]:
df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,0,Yes,4200,17
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,1,Yes,4999,22
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,0,Yes,13900,22
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,0,Yes,45000,7
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Black,Beige,0,Yes,97500,3

In [ ]:
df['fuel_type'].value_counts()

fuel_type
Gasoline          147394
E85 Flex Fuel       5235
Hybrid              5061
Diesel              3652
–                    755
Plug-In Hybrid       495
not supported         15
Name: count, dtype: int64

In [ ]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  object
 2   model         125690 non-null  object
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     122307 non-null  object
 6   engine        125690 non-null  object
 7   transmission  125690 non-null  object
 8   ext_col       125690 non-null  object
 9   int_col       125690 non-null  object
 10  accident      124058 non-null  float64
 11  clean_title   111451 non-null  object
 12  car_age       125690 non-null  int64
dtypes: float64(1), int64(4), object(8)
memory usage: 12.5+ MB

In [ ]:
df['fuel_type'] = df['fuel_type'].replace({'Gasoline': 0, 'Diesel':1, 'E85 Flex Fuel': 2, 'Hybrid':3, 'Plug-In Hybrid': 3, 'not supported': 4})
df=df[df['fuel_type'] != '–']

dt['fuel_type'] = dt['fuel_type'].replace({'Gasoline': 0, 'Diesel':1, 'E85 Flex Fuel': 2, 'Hybrid':3, 'Plug-In Hybrid': 3, 'not supported': 4})
# dt=dt[dt['fuel_type'] != '–']

In [ ]:
df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age
0,0,MINI,Cooper S Base,2007,213000,0,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,0,Yes,4200,17
1,1,Lincoln,LS V8,2002,143250,0,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,1,Yes,4999,22
2,2,Chevrolet,Silverado 2500 LT,2002,136731,2,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,0,Yes,13900,22
3,3,Genesis,G90 5.0 Ultimate,2017,19500,0,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,0,Yes,45000,7
4,4,Mercedes-Benz,Metris Base,2021,7388,0,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Black,Beige,0,Yes,97500,3

In [ ]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  object
 2   model         125690 non-null  object
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     122307 non-null  object
 6   engine        125690 non-null  object
 7   transmission  125690 non-null  object
 8   ext_col       125690 non-null  object
 9   int_col       125690 non-null  object
 10  accident      124058 non-null  float64
 11  clean_title   111451 non-null  object
 12  car_age       125690 non-null  int64
dtypes: float64(1), int64(4), object(8)
memory usage: 12.5+ MB

In [ ]:
df.loc[df['clean_title'].str.contains('Yes', na=False ), 'clean_title'] = 0

dt.loc[dt['clean_title'].str.contains('Yes', na=False ), 'clean_title'] = 0

In [ ]:
df['clean_title'].value_counts()

clean_title
0    161852
Name: count, dtype: int64

In [ ]:
df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age
0,0,MINI,Cooper S Base,2007,213000,0,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,0,0,4200,17
1,1,Lincoln,LS V8,2002,143250,0,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,1,0,4999,22
2,2,Chevrolet,Silverado 2500 LT,2002,136731,2,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,0,0,13900,22
3,3,Genesis,G90 5.0 Ultimate,2017,19500,0,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,0,0,45000,7
4,4,Mercedes-Benz,Metris Base,2021,7388,0,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Black,Beige,0,0,97500,3

In [ ]:
df['HP'] = df['engine'].str.extract(r'(\d+\.?\d*)(?=HP)').astype(float)
df['Liters'] = df['engine'].str.extract(r'(\d+\.?\d*)(?=L)').astype(float)

dt['HP'] = dt['engine'].str.extract(r'(\d+\.?\d*)(?=HP)').astype(float)
dt['Liters'] = dt['engine'].str.extract(r'(\d+\.?\d*)(?=L)').astype(float)
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  object
 2   model         125690 non-null  object
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     122307 non-null  object
 6   engine        125690 non-null  object
 7   transmission  125690 non-null  object
 8   ext_col       125690 non-null  object
 9   int_col       125690 non-null  object
 10  accident      124058 non-null  float64
 11  clean_title   111451 non-null  object
 12  car_age       125690 non-null  int64
 13  HP            103509 non-null  float64
 14  Liters        116283 non-null  float64
dtypes: float64(3), int64(4), object(8)
memory usage: 14.4+ MB

In [ ]:

df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age,HP,Liters
0,0,MINI,Cooper S Base,2007,213000,0,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,0,0,4200,17,172.0,1.6
1,1,Lincoln,LS V8,2002,143250,0,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,1,0,4999,22,252.0,3.9
2,2,Chevrolet,Silverado 2500 LT,2002,136731,2,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,0,0,13900,22,320.0,5.3
3,3,Genesis,G90 5.0 Ultimate,2017,19500,0,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,0,0,45000,7,420.0,5.0
4,4,Mercedes-Benz,Metris Base,2021,7388,0,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Black,Beige,0,0,97500,3,208.0,2.0

In [ ]:
df.drop(columns=['engine', 'int_col', 'ext_col', 'model', 'id'], inplace=True)
dt.drop(columns=['engine', 'int_col', 'ext_col', 'model', 'id' ], inplace=True)




df.head()

,brand,model_year,milage,fuel_type,transmission,accident,clean_title,price,car_age,HP,Liters
0,MINI,2007,213000,0,A/T,0,0,4200,17,172.0,1.6
1,Lincoln,2002,143250,0,A/T,1,0,4999,22,252.0,3.9
2,Chevrolet,2002,136731,2,A/T,0,0,13900,22,320.0,5.3
3,Genesis,2017,19500,0,Transmission w/Dual Shift Mode,0,0,45000,7,420.0,5.0
4,Mercedes-Benz,2021,7388,0,A/T,0,0,97500,3,208.0,2.0

In [ ]:

from sklearn.preprocessing import OneHotEncoder, LabelEncoder
label_encoder = LabelEncoder()
df['transmission'] = label_encoder.fit_transform(df['transmission'])
df['transmission'].fillna(df['transmission'].median(), inplace=True)

dt['transmission'] = label_encoder.fit_transform(dt['transmission'])
dt['transmission'].fillna(dt['transmission'].median(), inplace=True)

In [ ]:
df.head()

,brand,model_year,milage,fuel_type,transmission,accident,clean_title,price,car_age,HP,Liters
0,MINI,2007,213000,0,0,0,0,4200,17,172.0,1.6
1,Lincoln,2002,143250,0,0,1,0,4999,22,252.0,3.9
2,Chevrolet,2002,136731,2,0,0,0,13900,22,320.0,5.3
3,Genesis,2017,19500,0,3,0,0,45000,7,420.0,5.0
4,Mercedes-Benz,2021,7388,0,0,0,0,97500,3,208.0,2.0

In [ ]:
df['brand'] = label_encoder.fit_transform(df['brand'])
df['brand'].fillna(df['brand'].median(), inplace=True)

dt['brand'] = label_encoder.fit_transform(dt['brand'])
dt['brand'].fillna(df['brand'].median(), inplace=True)


df.head()

,brand,model_year,milage,fuel_type,transmission,accident,clean_title,price,car_age,HP,Liters
0,31,2007,213000,0,0,0,0,4200,17,172.0,1.6
1,28,2002,143250,0,0,1,0,4999,22,252.0,3.9
2,9,2002,136731,2,0,0,0,13900,22,320.0,5.3
3,16,2017,19500,0,3,0,0,45000,7,420.0,5.0
4,36,2021,7388,0,0,0,0,97500,3,208.0,2.0

In [ ]:
df.fillna(0, inplace=True)

In [ ]:
X = df.drop(['price'],axis=1)
y = df['price']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.4,random_state=42)

In [ ]:
model = LinearRegression()
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

rmse = mean_squared_error(y_test,y_pred, squared=False)

print(rmse)

74837.4899642434

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 161852 entries, 0 to 188532
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   brand         161852 non-null  int64
 1   model_year    161852 non-null  int64
 2   milage        161852 non-null  int64
 3   fuel_type     161852 non-null  object
 4   transmission  161852 non-null  int64
 5   accident      161852 non-null  int64
 6   clean_title   161852 non-null  object
 7   price         161852 non-null  int64
 8   car_age       161852 non-null  int64
 9   HP            161852 non-null  float64
 10  Liters        161852 non-null  float64
dtypes: float64(2), int64(7), object(2)
memory usage: 14.8+ MB

In [ ]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   brand         125690 non-null  int64
 1   model_year    125690 non-null  int64
 2   milage        125690 non-null  int64
 3   fuel_type     122307 non-null  object
 4   transmission  125690 non-null  int64
 5   accident      124058 non-null  float64
 6   clean_title   111451 non-null  object
 7   car_age       125690 non-null  int64
 8   HP            103509 non-null  float64
 9   Liters        116283 non-null  float64
dtypes: float64(3), int64(5), object(2)
memory usage: 9.6+ MB

In [ ]:
dt['fuel_type'] = dt['fuel_type'].replace("", "-" ,inplace=True)
dt.fillna(0, inplace=True)

In [ ]:
id = sf.pop('id')
y_pred = model.predict(dt)

# Create a submission DataFrame
submission_df = pd.DataFrame({
    'id': id,
    'class': y_pred
})

# Save the submission DataFrame to a CSV file
submission_df.to_csv('results.csv', index=False)
print("Submission file created: submission_file.csv")

Submission file created: submission_file.csv